### ISSUE TITLE
Wrong defaults for spectrewm desktop windows

### ISSUE THREAD

**Issue by vaskark** [jarcode-foss/glava#131]
I recently reported a build error for Ubuntu 19.04 and was advised to try using straight meson. Well, I did and am getting the same error as with make (which is just a wrapper anyway):

`meson.build:98:0: ERROR:  Include directory to be added is not an include directory object.`

Not sure what else I can do or report. It's a great app and I wish to keep up with its development.
Thanks.

P.S. It does not do desktop mode well on [spectrwm](https://github.com/conformal/spectrwm). Just thought I'd let you know :)

**Comment by wacossusca34** [comment]
I think I fixed this in the referenced commit, although note you were using an out-of-date glava tree since the line number from Meson does not match up to `master`. Seems to be an issue with older Meson versions not allowing the `include_directories` specifier to contain a string.

As for spectrwm desktop window compatibility there are a myriad of options you can try to get this to work. I have not tested spectrwm directly so there is currently no preset to ensure the best default behavior. See `setxwintype` and `addxwinstate` in `rc.glsl`.

The first thing you should try is `#setxwintype "!-"` to see if GLava behaves nicely if unmanaged. `!` instructs GLava to use _unmanaged windows_ which circumvent the WM, and the following characters dictate stacking order.

If there is a poor interaction with your WM that you cannot avoid with GLava's window parameters then please indicate so I can set some time aside to test it myself.

**Comment by vaskark** [comment]
@wacossusca34 Hi again.
I should have stated that I did a fresh checkout today before I made my post about the error. My bad. Same error for me, though. 

As for spectrum, I tried your suggestion and set 

`#request setxwintype “!-“`

GLava opens in window mode with a border, as before. I’ll keep playing with `addxwinstate` and see if it helps.

**Comment by wacossusca34** [comment]
@vaskark try:

```GLSL
#request setfloating true
#request setxwintype "desktop"
#request addxwinstate "below"
#request addxwinstate "pinned"
```

Alternatively with unmanaged windows:

```GLSL
#request setxwintype "!-"
#request setdecorated false
#request setforcegeometry true
```

Although I suspect unmanaged window types to have stacking issues on spectrwm.

I should note make sure you are trying these options _without_ the `--desktop` flag, as it automatically overrides some of these options.

**Comment by wacossusca34** [comment]
As for upstream build issues 69f25eb should have solved it. I am willing to bet that you had not pulled from the remote branch before trying to build, but to be absolutely certain I have removed the one `include_directories` specifier in 1974869 to avoid differing behavior across meson versions.

It would also be helpful to know what version of Meson you are using, as I cannot reproduce these build issues on `0.51.2`.

**Comment by vaskark** [comment]
@wacossusca34 These settings work!

```
#request setfloating true
#request setxwintype "!-"
#request addxwinstate "below"
#request addxwinstate "pinned"

#request setdecorated false
#request setforcegeometry true
```
Thanks so much. Will these be eventually included in a file called env_spectrwm.glsl? And I imagine these new settings may effect how GLava operates on i3, gnome, etc. Might have to set up different config files for whatever WM I’m using. 
Glad it’s working now :)

**Comment by wacossusca34** [comment]
@vaskark after I confirm it behaves as expected myself, yes. Keep in mind unmanaged windows ignore window state, so if you are using `"!-"` window types there is no point in having `"below"` or `"pinned"` hints.

I suspect spectrwm is in the same boat as i3 with not supporting desktop window types, so unmanaged windows are the last resort.

Thanks for letting me know spectrwm needs some special treatment beyond the default settings.

**Comment by vaskark** [comment]
> As for upstream build issues [69f25eb](https://github.com/wacossusca34/glava/commit/69f25eb44bb052a7d7934f351c7ebdca70e567c4) should have solved it. I am willing to bet that you had not pulled from the remote branch before trying to build, but to be absolutely certain I have removed the one `include_directories` specifier in [1974869](https://github.com/wacossusca34/glava/commit/1974869b5feb8c52779a5f99bac8849e955ea469) to avoid differing behavior across meson versions.
> 
> It would also be helpful to know what version of Meson you are using, as I cannot reproduce these build issues on `0.51.2`.

**Comment by wacossusca34** [comment]
I didn't actually _apply_ the defaults upstream yet so I'm re-opening this.

**Comment by vaskark** [comment]
@wacossusca34 My meson version is 0.49.0. So it's behind yours.

So if I make the env_*.glsl file I can get away with `glava --desktop` in any environment? Excellent.
Thanks for all your time and help. People like you are what make the internet a great place.

**Comment by wacossusca34** [comment]
@vaskark can you confirm if `master` works on Ubuntu's meson now? I would prefer older versions to work since there's one or two PPAs out there with glava in it, and it would make it easier to build packages for it.

**Comment by vaskark** [comment]
@wacossusca34 I just did a new checkout of master branch and received this error:

`meson.build:118:4: ERROR:  C library 'obs' not found`

**Comment by wacossusca34** [comment]
@vaskark Good, it's working. OBS is a new build (not runtime) requirement for upstream builds, which you can disable using `-Ddisable_obs=true` or the compatibility `Makefile`.

Also, if you are making a defaults file for your WM, make sure the name is set accordingly. Use:

```bash
xprop -id `xprop -root | grep _NET_SUPPORTING_WM_CHECK | head -n 1 | grep -oP '(?<= # ).*'` | grep _NET_WM_NAME | awk '{print $3}'
```

To not-so-elegantly get the exact name string of the currently running WM (the same string that glava uses internally).

**Comment by vaskark** [comment]
@wacossusca34 

Ok, I built with `meson -Ddisable_obs=true build` and it worked. But when I ran glava I got:

`glava: error while loading shared libraries: libglava.so: cannot open shared object file: No such file or directory
`

I've confirmed that I do indeed have that file (/usr/local/lib/x86_64-linux-gnu/libglava.so).
Whew! Frustrating :)

**Comment by vaskark** [comment]
@wacossusca34 I ran `sudo ldconfig` and it works now.

I've created` env_spectrwm.glsl `but it's being ignored when I run `glava -d.` I need to use a script that points to `rc-spectrwm.glsl` using --entry in order to get it to work right.

**Comment by wacossusca34** [comment]
@vaskark no, the `env_*.glsl` files are used internally when the `--desktop`/`-d` flag is used regardless of the entry point. The settings in the environment file overload any settings in the entry point.

**Comment by vaskark** [comment]
@wacossusca34 Okay, here's what I have in env_spectrwm.glsl:

```
#request setxwintype "!-"
#request setfloating  true
#request setdecorated false
#request setforcegeometry true
```

But `glava --desktop` just produces glava in a window on spectrwm.
I'm probably messing something up, making a noob mistake.

**Comment by wacossusca34** [comment]
@vaskark Double check that the file is named correctly and that you have the environment file placed in `/usr/xdg/glava` (a38f79e and onward) or `~/.config/glava` for older versions (or just both).

I just made a38f79e now since I just realized it makes little sense to have these files copied by `glava -C`, polluting the user config. Environment settings are meant to be an implementation detail to the `--desktop` flag anyway.

**Comment by wacossusca34** [comment]
I should also note that if you want a more interactive discussion you can always message me on freenode via user `Jarcode`.

**Comment by vaskark** [comment]
@wacossusca34 I placed the `env_spectrwm.glsl` file in /etc/xdg/glava folder (I assume you made a typo) as well as ~/.config/glava. It is named correctly based on the xprop command you provided earlier. Same problem. `glava --desktop` opens in a window.

But it does work when I use a specific entry file with the spectrwm settings. So at least I have that ;)

Thanks for the freenode invite. It's been years since I've been on irc so I might have to refresh my skills before I take that route.

Once again, many thanks for your help.

**Comment by vaskark** [comment]
@wacossusca34 Hmm. I just did another checkout and build. `glava --desktop` works now.

**Comment by jarcode-foss** [comment]
@vaskark I have added the environment file for spectrwm, so feel free to test 9abaafd. It only uses the unmanaged window type (`#request setxwintype "!-"`) as no other settings should be required.

I may remove a handful of environment files, including this one, before even making a version release since I can check for `_NET_WM_WINDOW_TYPE_DESKTOP` from `_NET_SUPPORTED` on the root window to determine if unmanaged windows are required for `--desktop` in a WM-independent fashion.
