### ISSUE TITLE
C library 'lua' no found

### ISSUE THREAD

**Issue by vaskark** [jarcode-foss/glava#133]
Hi again. I'm encountering a build error with the latest checkout (on Ubuntu 19.04):

`meson.build:125:2: ERROR:  C library 'lua' not found`

I have all the dependencies listed. I'm building with:

`meson -Ddisable_obs=true -Dprefix=/usr/local build`

Thanks.

**Comment by jarcode-foss** [comment]
Lua is a new dependency for `glava-config`. You can install it using your distro's Lua 5.3 package.

There is also no reason to _use_ `glava-config` since it is incomplete. I am committing these changes upstream since these changes do not break `glava-cli` (or `glava-obs`) and bring along minor fixes for those who want to follow it. For now, you sould use `-Ddisable_config=true`.

I am preparing for a major version release so don't forget to pay attention to changing build requirements in the `README.md`

**Comment by jarcode-foss** [comment]
If you were on Ubuntu/Debian, GLava now explicitly links to `lua5.3` as the `lua` dependency is not symlinked to Lua 5.3 on that distribution, so any issues there should be fixed (see 112e371). `glava-config` is also disabled in builds by default until I complete it, sorry for the inconvenience.
