### ISSUE TITLE
Support alsa 

### ISSUE THREAD

**Issue by HumanG33k** [jarcode-foss/glava#137]
Hello, 
I not and will not use pulse audio.
i use alsa. 
Glava can and will support alsa ? 
maybe through a meson option ?
i try with apulse but i have some error : 
```bash
apulse ./glava
WARNING: using "window" transform explicitlyop); implied from "fft" transform.
WARNING: using "gravity" transform explicitl-op); implied from "fft" transform.
WARNING: using "avg" transform explicitly is; implied from "fft" transform.
Could not open pulseaudio mainloop to find d 0
check if pulseaudio is running
```
but i guess it s because it use directly pulseaudio api ? 

thx

**Comment by HumanG33k** [comment]
I just rebuild from :
```bash 
meson --reconfigure build --prefix /usr -Dstandalone=true -Dbuildtype=debug  && ninja -C build
```
i add the debug option and the reconfigure 

and now it s look better 
```bash 
apulse ./glava --desktop
shaders folder 'userconf/bars' does not exist!failed to load shader 'userconf/util/smooth_pass.frag': No such file or directory
```
i run it from build after a config copy. I use I3. and i have not set dimensions in rc.glsl .

I also add my compilation output : 
```bash
The Meson build system
Version: 0.51.2
Source dir: /home/user/src/glava
Build dir: /home/user/src/glava/build
Build type: native build
Project name: glava
Project version: v1.6.3-87-g3cc5e22
C compiler for the host machine: ccache cc (gcc 9.2.1 "cc (Debian 9.2.1-8) 9.2.1 20190909")
C++ compiler for the host machine: ccache c++ (gcc 9.2.1 "c++ (Debian 9.2.1-8) 9.2.1 20190909")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES (cached)
Library pulse found: YES
Library pulse-simple found: YES
Library dl found: YES
Library m found: YES
Library X11 found: YES
Library Xext found: YES
Library Xrender found: YES
Library dl found: YES
Dependency threads found: YES (cached)
Library GL found: YES
Library X11 found: YES
Library obs found: YES
Library dl found: YES
Build targets in project: 4
Option buildtype is: debug [default: release]
Option optimization is: 0 [default: 2]
Found ninja-1.9.0 at /usr/bin/ninja
ninja: Entering directory `build'
[1/19] Compiling C object 'glava@sha/glava_glava.c.o'.
../glava/glava.c:53: warning: "SHADER_INSTALL_PATH" redefined
   53 | #define SHADER_INSTALL_PATH "../shaders/glava"
      | 
<command-line>: note: this is the location of the previous definition
[9/19] Compiling C object 'glava@exe/glava-cli_cli.c.o'.
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
[19/19] Linking target glava.
```
for the gcc/++ option i think i have somewhere an alias. (but i don t find it with the alias command)

**Comment by jarcode-foss** [comment]
You're free to use `apulse` (which may work if it can correctly handle re-sampling), but a proper ALSA backend is not a priority right now.

The deprecated warnings are currently harmless. Your second build configuration also makes no sense since you specified a prefix with a standalone build, and a debug build when you are not debugging the application.

In the coming weeks `apulse` will likely work better since I am working on merging some much larger changes to how audio updates function (shader re-sampling and using the native device sampling rate), but this assumes `apulse` correctly reflects data when GLava polls this information from the device.

I would also like to remind people who refuse to run a sound server that using ALSA alone poses a number of problems, namely different configurations causing a multitude of problems with how GLava polls for information and samples from the underlying device, and also forces the client to handle all resampling which will still be problematic in the future on systems that aren't GL 4.x capable (compute shader availability).

In the meantime, use PulseAudio. If you are erroneously associating high PulseAudio CPU usage when GLava is running with poor PulseAudio code, you are mistaken; this is because it is trying to resample in a way that avoids aliasing and GLava is requesting a rate not supported by the underlying device -- which will change in the future anyway.

**Comment by HumanG33k** [comment]
agree with you.

the error with shader remain even with a no debug only standalone build :

```bash
meson --reconfigure build -Dstandalone=true && ninja -C build
cd build
apulse ./glava --desktop
shaders folder 'userconf/bars' does not exist!failed to load shader 'userconf/util/smooth_pass.frag': No such file or directory
```
but i probably miss something from the doc ?


I use alsa because i use not mostly use software. in order to show how software work on it.
